name = "cloudflare-worker-template"
main = "main.ts"
compatibility_date = "2025-03-26"
dev.port = 3000
routes = [
  { pattern = "xymake.com", custom_domain = true },
  { pattern = "www.xymake.com", custom_domain = true }
]

[[kv_namespaces]]
binding = "CONTENT_KV"
id = "26855cd211be4d24994e43646c1164be"