name = "cloudflare-worker-template"
main = "main.ts"
compatibility_date = "2025-03-26"
dev.port = 3000
assets.directory = "./public"
route.custom_domain = true
route.pattern = "worker.wilmake.com"

[[kv_namespaces]]
binding = "CONTENT_KV"
id = "26855cd211be4d24994e43646c1164be"